ktor:
  application:
    modules:
      - io.davinci.ApplicationKt.module
  development: true
  deployment:
    port: 8080
    watch:
      - classes
      - resources
  secrets:
    trello: 0f8d5021c6c34491c09a65c10026d9ae
    openai: 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
